using Microsoft.EntityFrameworkCore.Migrations;

namespace AutoPay.DataLayer.Migrations
{
    public partial class Country : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Countries",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false),
                    Code = table.Column<string>(maxLength: 8, nullable: true),
                    Name = table.Column<string>(maxLength: 256, nullable: true),
                    Order = table.Column<int>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Countries", x => x.Id);
                });

            migrationBuilder.InsertData(
                table: "Countries",
                columns: new[] { "Id", "Code", "Name", "Order" },
                values: new object[,]
                {
                    { 1, "AD", "Andorra", 1 },
                    { 162, "NO", "Norway", 1 },
                    { 163, "NP", "Nepal", 1 },
                    { 164, "NR", "Nauru", 1 },
                    { 165, "NU", "Niue", 1 },
                    { 166, "NZ", "New Zealand", 1 },
                    { 167, "OM", "Oman", 1 },
                    { 168, "PA", "Panama", 1 },
                    { 169, "PE", "Peru", 1 },
                    { 170, "PF", "French Polynesia", 1 },
                    { 171, "PG", "Papua New Guinea", 1 },
                    { 172, "PH", "Philippines", 1 },
                    { 173, "PK", "Pakistan", 1 },
                    { 174, "PL", "Poland", 1 },
                    { 161, "NL", "Netherlands", 1 },
                    { 175, "PM", "Saint Pierre and Miquelon", 1 },
                    { 177, "PR", "Puerto Rico", 1 },
                    { 178, "PS", "Palestinian Territory", 1 },
                    { 179, "PT", "Portugal", 1 },
                    { 180, "PW", "Palau", 1 },
                    { 181, "PY", "Paraguay", 1 },
                    { 182, "QA", "Qatar", 1 },
                    { 183, "RE", "Reunion", 1 },
                    { 184, "RO", "Romania", 1 },
                    { 185, "RU", "Russian Federation", 1 },
                    { 186, "RW", "Rwanda", 1 },
                    { 187, "SA", "Saudi Arabia", 1 },
                    { 188, "SB", "Solomon Islands", 1 },
                    { 189, "SC", "Seychelles", 1 },
                    { 176, "PN", "Pitcairn", 1 },
                    { 190, "SD", "Sudan", 1 },
                    { 160, "NI", "Nicaragua", 1 },
                    { 158, "NF", "Norfolk Island", 1 },
                    { 130, "LT", "Lithuania", 1 },
                    { 131, "LU", "Luxembourg", 1 },
                    { 132, "LV", "Latvia", 1 },
                    { 133, "LY", "Libya", 1 },
                    { 134, "MA", "Morocco", 1 },
                    { 135, "MC", "Monaco", 1 },
                    { 136, "MD", "Moldova", 1 },
                    { 137, "MG", "Madagascar", 1 },
                    { 138, "MH", "Marshall Islands", 1 },
                    { 139, "MK", "Macedonia", 1 },
                    { 140, "ML", "Mali", 1 },
                    { 141, "MM", "Myanmar", 1 },
                    { 142, "MN", "Mongolia", 1 },
                    { 159, "NG", "Nigeria", 1 },
                    { 143, "MO", "Macao", 1 },
                    { 145, "MQ", "Martinique", 1 },
                    { 146, "MR", "Mauritania", 1 },
                    { 147, "MS", "Montserrat", 1 },
                    { 148, "MT", "Malta", 1 },
                    { 149, "MU", "Mauritius", 1 },
                    { 150, "MV", "Maldives", 1 },
                    { 151, "MW", "Malawi", 1 },
                    { 152, "MX", "Mexico", 1 },
                    { 153, "MY", "Malaysia", 1 },
                    { 154, "MZ", "Mozambique", 1 },
                    { 155, "NA", "Namibia", 1 },
                    { 156, "NC", "New Caledonia", 1 },
                    { 157, "NE", "Niger", 1 },
                    { 144, "MP", "Northern Mariana Islands", 1 },
                    { 129, "LS", "Lesotho", 1 },
                    { 191, "SE", "Sweden", 1 },
                    { 193, "SH", "Saint Helena", 1 },
                    { 226, "UK", "United Kingdom", 0 },
                    { 227, "UM", "United States Minor Outlying Islands", 1 },
                    { 228, "US", "United States", 0 },
                    { 229, "UY", "Uruguay", 1 },
                    { 230, "UZ", "Uzbekistan", 1 },
                    { 231, "VA", "Vatican City State (Holy See)", 1 },
                    { 232, "VC", "Saint Vincent and the Grenadines", 1 },
                    { 233, "VE", "Venezuela", 1 },
                    { 234, "VG", "Virgin Islands (British)", 1 },
                    { 235, "VI", "Virgin Islands (U.S.)", 1 },
                    { 236, "VN", "Viet Nam", 1 },
                    { 237, "VU", "Vanuatu", 1 },
                    { 238, "WF", "Wallis and Futuna", 1 },
                    { 225, "UG", "Uganda", 1 },
                    { 239, "WS", "Samoa", 1 },
                    { 241, "YT", "Mayotte", 1 },
                    { 242, "YU", "Yugoslavia (former)", 1 },
                    { 243, "ZA", "South Africa", 1 },
                    { 244, "ZM", "Zambia", 1 },
                    { 245, "ZR", "Zaire (former)", 1 },
                    { 246, "ZW", "Zimbabwe", 1 },
                    { 251, "CH", "Switzerland", 1 },
                    { 252, "CH", "Switzerland", 1 },
                    { 267, "NO", "Norway", 1 },
                    { 269, "SP", "Serbia", 1 },
                    { 275, "ZZ", "Uknown", 1 },
                    { 276, "IM", "Isle of Man", 1 },
                    { 277, "AP", "Asia/Pacific Region", 1 },
                    { 240, "YE", "Yemen", 1 },
                    { 192, "SG", "Singapore", 1 },
                    { 224, "UA", "Ukraine", 1 },
                    { 222, "TW", "Taiwan", 1 },
                    { 194, "SI", "Slovenia", 1 },
                    { 195, "SJ", "Svalbard and Jan Mayen", 1 },
                    { 196, "SK", "Slovakia", 1 },
                    { 197, "SL", "Sierra Leone", 1 },
                    { 198, "SM", "San Marino", 1 },
                    { 199, "SN", "Senegal", 1 },
                    { 200, "SO", "Somalia", 1 },
                    { 201, "SR", "Suriname", 1 },
                    { 202, "ST", "Sao Tome and Principe", 1 },
                    { 203, "SU", "USSR (former)", 1 },
                    { 204, "SV", "El Salvador", 1 },
                    { 205, "SY", "Syria", 1 },
                    { 206, "SZ", "Swaziland", 1 },
                    { 223, "TZ", "Tanzania", 1 },
                    { 207, "TC", "Turks and Caicos Islands", 1 },
                    { 209, "TF", "French Southern Territories", 1 },
                    { 210, "TG", "Togo", 1 },
                    { 211, "TH", "Thailand", 1 },
                    { 212, "TJ", "Tajikistan", 1 },
                    { 213, "TK", "Tokelau", 1 },
                    { 214, "TL", "Timor-Leste", 1 },
                    { 215, "TM", "Turkmenistan", 1 },
                    { 216, "TN", "Tunisia", 1 },
                    { 217, "TO", "Tonga", 1 },
                    { 218, "TP", "East Timor", 1 },
                    { 219, "TR", "Turkey", 1 },
                    { 220, "TT", "Trinidad and Tobago", 1 },
                    { 221, "TV", "Tuvalu", 1 },
                    { 208, "TD", "Chad", 1 },
                    { 278, "GE", "Guernsey", 1 },
                    { 128, "LR", "Liberia", 1 },
                    { 126, "LI", "Liechtenstein", 1 },
                    { 34, "BW", "Botswana", 1 },
                    { 35, "BY", "Belarus", 1 },
                    { 36, "BZ", "Belize", 1 },
                    { 37, "CA", "Canada", 1 },
                    { 38, "CC", "Cocos (Keeling) Islands", 1 },
                    { 39, "CD", "Democratic Republic of the Congo", 1 },
                    { 40, "CF", "Central African Republic", 1 },
                    { 41, "CG", "Congo", 1 },
                    { 42, "CH", "Switzerland", 1 },
                    { 43, "CI", "Cote D'Ivoire(Ivory Coast)", 1 },
                    { 44, "CK", "Cook Islands", 1 },
                    { 45, "CL", "Chile", 1 },
                    { 46, "CM", "Cameroon", 1 },
                    { 33, "BV", "Bouvet Island", 1 },
                    { 47, "CN", "China", 1 },
                    { 49, "CR", "Costa Rica", 1 },
                    { 50, "CS", "Serbia and Montenegro", 1 },
                    { 51, "CU", "Cuba", 1 },
                    { 52, "CV", "Cape Verde", 1 },
                    { 53, "CX", "Christmas Island", 1 },
                    { 54, "CY", "Cyprus", 1 },
                    { 55, "CZ", "Czech Republic", 1 },
                    { 56, "DE", "Germany", 1 },
                    { 57, "DJ", "Djibouti", 1 },
                    { 58, "DK", "Denmark", 1 },
                    { 59, "DM", "Dominica", 1 },
                    { 60, "DO", "Dominican Republic", 1 },
                    { 61, "DZ", "Algeria", 1 },
                    { 48, "CO", "Colombia", 1 },
                    { 62, "EC", "Ecuador", 1 },
                    { 32, "BT", "Bhutan", 1 },
                    { 30, "BR", "Brazil", 1 },
                    { 2, "AE", "United Arab Emirates", 1 },
                    { 3, "AF", "Afghanistan", 1 },
                    { 4, "AG", "Antigua and Barbuda", 1 },
                    { 5, "AI", "Anguilla", 1 },
                    { 6, "AL", "Albania", 1 },
                    { 7, "AM", "Armenia", 1 },
                    { 8, "AN", "Netherlands Antilles", 1 },
                    { 9, "AO", "Angola", 1 },
                    { 10, "AQ", "Antarctica", 1 },
                    { 11, "AR", "Argentina", 1 },
                    { 12, "AS", "American Samoa", 1 },
                    { 13, "AT", "Austria", 1 },
                    { 14, "AU", "Australia", 0 },
                    { 31, "BS", "Bahamas", 1 },
                    { 15, "AW", "Aruba", 1 },
                    { 17, "AZ", "Azerbaijan", 1 },
                    { 18, "BA", "Bosnia and Herzegovina", 1 },
                    { 19, "BB", "Barbados", 1 },
                    { 20, "BD", "Bangladesh", 1 },
                    { 21, "BE", "Belgium", 1 },
                    { 22, "BF", "Burkina Faso", 1 },
                    { 23, "BG", "Bulgaria", 1 },
                    { 24, "BH", "Bahrain", 1 },
                    { 25, "BI", "Burundi", 1 },
                    { 26, "BJ", "Benin", 1 },
                    { 27, "BM", "Bermuda", 1 },
                    { 28, "BN", "Brunei Darussalam", 1 },
                    { 29, "BO", "Bolivia", 1 },
                    { 16, "AX", "Aland Islands", 1 },
                    { 127, "LK", "Sri Lanka", 1 },
                    { 63, "EE", "Estonia", 1 },
                    { 65, "EH", "Western Sahara", 1 },
                    { 98, "HT", "Haiti", 1 },
                    { 99, "HU", "Hungary", 1 },
                    { 100, "ID", "Indonesia", 1 },
                    { 101, "IE", "Ireland", 1 },
                    { 102, "IL", "Israel", 1 },
                    { 103, "IN", "India", 0 },
                    { 104, "IO", "British Indian Ocean Territory", 1 },
                    { 105, "IQ", "Iraq", 1 },
                    { 106, "IR", "Iran", 1 },
                    { 107, "IS", "Iceland", 1 },
                    { 108, "IT", "Italy", 1 },
                    { 109, "JM", "Jamaica", 1 },
                    { 110, "JO", "Jordan", 1 },
                    { 97, "HR", "Croatia (Hrvatska)", 1 },
                    { 111, "JP", "Japan", 1 },
                    { 113, "KG", "Kyrgyzstan", 1 },
                    { 114, "KH", "Cambodia", 1 },
                    { 115, "KI", "Kiribati", 1 },
                    { 116, "KM", "Comoros", 1 },
                    { 117, "KN", "Saint Kitts and Nevis", 1 },
                    { 118, "KP", "Korea (North)", 1 },
                    { 119, "KR", "Korea (South)", 1 },
                    { 120, "KW", "Kuwait", 1 },
                    { 121, "KY", "Cayman Islands", 1 },
                    { 122, "KZ", "Kazakhstan", 1 },
                    { 123, "LA", "Laos", 1 },
                    { 124, "LB", "Lebanon", 1 },
                    { 125, "LC", "Saint Lucia", 1 },
                    { 112, "KE", "Kenya", 1 },
                    { 64, "EG", "Egypt", 1 },
                    { 96, "HN", "Honduras", 1 },
                    { 94, "HK", "Hong Kong", 1 },
                    { 66, "ER", "Eritrea", 1 },
                    { 67, "ES", "Spain", 1 },
                    { 68, "ET", "Ethiopia", 1 },
                    { 69, "FI", "Finland", 1 },
                    { 70, "FJ", "Fiji", 1 },
                    { 71, "FK", "Falkland Islands (Malvinas)", 1 },
                    { 72, "FM", "Federated States of Micronesia", 1 },
                    { 73, "FO", "Faroe Islands", 1 },
                    { 74, "FR", "France", 1 },
                    { 75, "FX", "France, Metropolitan", 1 },
                    { 76, "GA", "Gabon", 1 },
                    { 77, "GB", "Great Britain (UK)", 1 },
                    { 78, "GD", "Grenada", 1 },
                    { 95, "HM", "Heard Island and McDonald Islands", 1 },
                    { 79, "GE", "Georgia", 1 },
                    { 81, "GH", "Ghana", 1 },
                    { 82, "GI", "Gibraltar", 1 },
                    { 83, "GL", "Greenland", 1 },
                    { 84, "GM", "Gambia", 1 },
                    { 85, "GN", "Guinea", 1 },
                    { 86, "GP", "Guadeloupe", 1 },
                    { 87, "GQ", "Equatorial Guinea", 1 },
                    { 88, "GR", "Greece", 1 },
                    { 89, "GS", "S. Georgia and S. Sandwich Islands", 1 },
                    { 90, "GT", "Guatemala", 1 },
                    { 91, "GU", "Guam", 1 },
                    { 92, "GW", "Guinea-Bissau", 1 },
                    { 93, "GY", "Guyana", 1 },
                    { 80, "GF", "French Guiana", 1 },
                    { 279, "AD", "Andorra", 1 }
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Countries");
        }
    }
}
